# Generated by Django 4.1.3 on 2024-02-20 20:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_currency_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
